### ISSUE TITLE
Does this work on Mac OSX?

### ISSUE THREAD

**Issue by stormbytes** [ukBaz/BLE_GATT#6]
This is a really terrific library. There's virtually nothing like this (that I can find) for Mac OSX and so I'm wondering if this would work with the mac?

edit: Just saw that this is based on BlueZ which as I understand is Linux-only. Might want to add Mac OSX support to future releases? Would certainly be popular I think.

**Comment by ukBaz** [comment]
Thank you for your kind words about the library. 

I have no plans to extend this library to Mac OSX mainly because I don't have easy access to the hardware.

I do attempt to maintain a list of other Python Bluetooth libraries, some of which are attempting to be be cross-platform:
https://github.com/ukBaz/python-bluezero/wiki

Thanks again for your interest, but I'm going to close this issue.
